/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.io.IOException;
import java.security.GeneralSecurityException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SheetsAndJava sheetsAndJava = new SheetsAndJava();
        try {
            sheetsAndJava.start();
        } catch (IOException | GeneralSecurityException e) {
            throw new RuntimeException(e);
        }

        try {
            new PDF().generatePDF(sheetsAndJava.getProfessors());
        } catch (IOException e) {
            System.err.println(e);
        }
    }
}
